version: "3.8"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  cid-checker-frontend:
    image: cid-checker-frontend
    restart: always
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    volumes:
      - ./packages/frontend:/app/packages/frontend
  cid-checker-api:
    image: cid-checker-api
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app

  cid-checker-watcher:
    image: cid-checker-watcher
    restart: always
    build:
      context: .
      dockerfile: ./packages/watcher/Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./:/app

  caddy:
    image: caddy:2.4.3-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./502.html:/srv/502.html
      - caddy_data:/data

volumes:
  caddy_data:

