version: "3.8"

services:

  cid-checker-frontend:
    hostname: cid-checker-frontend
    container_name: cid-checker-frontend
    image: cid-checker-frontend:1.0.0
    restart: always
    ports:
      - 8080:8080

  cid-checker-backend:
    hostname: cid-checker-backend
    container_name: cid-checker-backend
    image: cid-checker-backend:1.0.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - "./packages/backend/.env:/app/packages/backend/.env"

  cid-checker-watcher:
    hostname: cid-checker-watcher
    container_name: cid-checker-watcher
    image: cid-checker-watcher:1.0.0
    restart: always
    volumes:
      - "./packages/watcher/.env:/app/packages/watcher/.env"

networks:
    default:
        external:
            name: cid-checker
