version: "3.8"

services:

  cid-checker-frontend:
    hostname: cid-checker-frontend
    container_name: cid-checker-frontend
    image: cid-checker-frontend:1.0.0
    restart: always
    ports:
      - 8080:8080

  cid-checker-backend:
    hostname: cid-checker-backend
    container_name: cid-checker-backend
    image: cid-checker-backend:1.0.0
    restart: always
    environment:
      NODE_ENV: "${NODE_ENV}"
      PORT: "${PORT}"
      CID_DB_CONNECTIONSTRING: "${CID_DB_CONNECTIONSTRING}"
      CID_DB_NAME: "${CID_DB_NAME}"
      CID_DATABASE_USER: "${CID_DATABASE_USER}"
      CID_DATABASE_PASSWORD: "${CID_DATABASE_PASSWORD}"
      CID_DB_CA_FILE: "${CID_DB_CA_FILE}"
      CID_LOTUS_RPCURL: "${CID_DB_CA_FILE}"
      CID_LOTUS_JWT_TOKEN: "${CID_DB_CA_FILE}"

  cid-checker-watcher:
    hostname: cid-checker-watcher
    container_name: cid-checker-watcher
    image: cid-checker-watcher:1.0.0
    restart: always
    environment:
      NODE_ENV: "${NODE_ENV}"
      SLEEP_TIPSET_CHECK_MS: "${SLEEP_TIPSET_CHECK_MS}"
      DEBUG_FD: "${DEBUG_FD}"
      CID_DB_CONNECTIONSTRING: "${CID_DB_CONNECTIONSTRING}"
      CID_DB_NAME: "${CID_DB_NAME}"
      CID_DATABASE_USER: "${CID_DATABASE_USER}"
      CID_DATABASE_PASSWORD: "${CID_DATABASE_PASSWORD}"
      CID_DB_CA_FILE: "${CID_DB_CA_FILE}"
      CID_LOTUS_RPCURL: "${CID_DB_CA_FILE}"
      CID_LOTUS_JWT_TOKEN: "${CID_DB_CA_FILE}"
