name: CID Checker CI/CD Pipeline
on:
  push:
    branches: [ main, update-ci-cd-workflow ]

jobs:   
  deployment:
    runs-on: ubuntu-latest
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2
      - name: Copy config files to root directory
        run: |
          mv ./.config/appspec.yml ./appspec.yml && \
          mv ./.config/nginx.conf ./nginx.conf && \
          mv ./.config/mime.types ./mime.types
        working-directory: ./
      # Step 3
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          mv ./.github/nginx.conf ./nginx.conf && \
          mv ./.github/mime.types ./mime.types && \
          aws deploy create-deployment \
            --application-name CID-Checker \
            --deployment-group-name CID-Checker-Deployment-Group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
